version: "3.8"
services:
  web_app:
    #build: .
    image: "library/node:14"
    working_dir: '/usr/src'
    volumes:
      - '.:/usr/src/app_local'
    ports:
      - '8080:8080'
    #stdin_open: true # docker run -i
    #tty: true        # docker run -t
    command: "bash -c 'apt-get update && apt-get install dos2unix && dos2unix -n app_local/bootup.sh bootup.sh && bash bootup.sh ${REPOSITORY}'"
