version: "3.8"
services:
  web_app:
    #build: .
    image: "niborus/eu-seite:latest"
    working_dir: '/usr/src'
    volumes:
      - '.:/usr/src/app_local'
    ports:
      - '8080:8080'
    #stdin_open: true # docker run -i
    #tty: true        # docker run -t
    command: "./bootup.sh ${REPOSITORY}"
